SELECT STREET_ADDRESS, 
    CITY, 
    COUNTRY_NAME 
FROM 
    hr.locations local 
    JOIN hr.countries pais 
    ON local.COUNTRY_ID = pais.COUNTRY_ID;

SELECT DEPARTMENT_ID, 
    DEPARTMENT_NAME, 
    MANAGER_ID
FROM hr.departments order by DEPARTMENT_NAME;

SELECT STREET_ADDRESS
FROM hr.locations WHERE SUBSTR(STREET_ADDRESS, INSTR(STREET_ADDRESS, ' ') + 1, 1) = 'V';

SELECT EMAIL,
	PHONE_NUMBER
FROM hr.employees WHERE EXTRACT(YEAR FROM HIRE_DATE) = 2008;

SELECT * FROM oe.ORDERS WHERE ORDER_TOTAL > 10000
SELECT * FROM oe.PRODUCT_INFORMATION WHERE PRODUCT_STATUS = 'under development' OR PRODUCT_STATUS = 'orderable'
SELECT * FROM oe.CUSTOMERS WHERE CREDIT_LIMIT BETWEEN 500 AND 700;
SELECT * FROM oe.CUSTOMERS WHERE GENDER = 'F' and MARITAL_STATUS = 'married';
